### ISSUE TITLE
Change Mutable Locator to have SetLocator() method.

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/splat#276] opened 2019-02-11 00:57 UTC
As per @dpvreony comment in a recent issue. We should probably more the Locator's method to a `SetLocator()` method so we can avoid some confusion about the two setters on both properties. This is a breaking change so v7 is likely a good target for this change.

```cs
public interface IDependencyResolver : IReadonlyDependencyResolver, IMutableDependencyResolver
{
// remove the get methods
}

// Locator.Current could be changed to expose this
public interface IReadonlyDependencyResolver
{
// put get methods in here
}
```

_Originally posted by @dpvreony in https://github.com/reactiveui/splat/issues/265#issuecomment-461933630_

**Comment by worldbeater** [comment] 2019-02-16 08:16
Another thing. Currently, it isn't obvious that methods like `container.UseDryIocDependencyResolver()` really initialize dependency resolver belonging to Splat (and to ReactiveUI as well). Maybe instead of extending [container-specific kernel](https://github.com/reactiveui/splat/blob/master/src/Splat.DryIoc/SplatDryIocExtensions.cs#L22) it's better and more obvious to extend `Locator.Current` (or static `Locator`) to make the initialization process more intuitive. Another way to resolve this is maybe renaming those container-specific extensions to `InitializeSplat()` etc.

API that we currently have:
```cs
var container = new Container();
container.Register<IViewFor<MainViewModel>, MainPage>();
container.Register<MainViewModel>();
container.UseDryIocDependencyResolver(); // Will it really initialize Splat?
```
This may be more obvious:
```cs
container.UseDryIocAsSplatDependencyResolver();
```
Or this:
```cs
Locator.UseDryIocDependencyResolver(container);
```

cc @RLittlesII @glennawatson @dpvreony

**Comment by RLittlesII** [comment] 2019-02-16 17:44
I agree that adding these adapters is not intuitive, but that can potentially be solved with documentation?

All the "convenience" extension methods do is hide the assignment of `Locator.CurrrentMutable = new DependencyResolver(container)`.  I actually even questioned @glennawatson on whether they had value after we made them so light weight.

I will say as someone who uses one of these dependency resolver for Splat, that I am doing so to hide Splats existence to my application.  I don't want any reference to the `Locator` in my code if I can help it.  So the thought was to put the onus of the container to assign itself to Splat.  That way from an API perspective, all your dealings are with is the container you are comfortable with.  Up until the point you have to actually assign the dependency resolver adapter, you haven't interacted with Splat at all.  You can register dependencies for an entire application without having to know the Locator exists, which seems like the point of using one of these adapters.

The naming convention leaves some to be desired.  It is already verbose, but what you are doing is assigning your container as the `IMutableDependencyResolver`  implementation for Splat, so the `SetLocator` concept makes sense.  Maybe `SetAdapter`?  The initialization of Splat and ReactiveUI aren't obvious.  They are the results of the assignment, not the cause.

All that to say.  `Locator.SetLocator(new DependencyResolver(container))` is basically what the extension method would be doing anyway.  If we wanted to pass the container itself in `Locator.SetLocator(container)` I think we'd have to take the dependency on each IOC container in Splat proper.

I know @glennawatson has some thoughts on changes he'd like to make to Splat.  Hopefully some of those will address a lot of these concerns.

**Comment by glennawatson** [comment] 2019-02-16 18:46
I was thinking of 

```cs
public class Locator
{
   Locator.SetLocator(IMutableDependencyResolver locator) { /* locator stuff */ }
}
```

```cs
public static class ExtensionsForDryIOC
{
   public void SetLocator(Container dryIocContainer) => Locator.SetLocator(new DependencyResolver(container));
}
```

Could that work, removes the need for doing the wrapping stuff.

**Comment by dpvreony** [comment] 2019-02-19 20:27
made an initial start. i still need to sense check it when on my proper dev machine

**Closed** 2019-02-27 08:26 UTC
Labels: developer-experience
