### ISSUE TITLE
[BUG] System.Reflection.TargetInvocationException on BitmapLoader.Current

### ISSUE THREAD

**Issue by IamTobi** [reactiveui/splat#330] opened 2019-05-28 12:03 UTC
**Describe the bug**
I am using akavache and LoadImageFromUrl(key,url,fetchalways,...) method. As I can see this calls the BitmapLoader.Current.Load() method this throws an exception. Possible the Reflection of the PlatformBitmapLoader fails when BitmapLoader.Current is called

**Expected behavior**
An image is loaded 😁 

**Environment(please complete the following information):**
 - OS: Android (iOS is fine)
- Akavache: 5.0.0 (can't use any other right now)
- Splat: 3.0.0 (can't use any other right now)

**Additional context**
```
{
    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.-- - > System.TypeInitializationException: The type initializer
    for 'Splat.PlatformBitmapLoader'
    threw an exception.-- - > System.InvalidOperationException: Sequence contains no matching element
    at System.Linq.Enumerable.First[TSource](System.Collections.Generic.IEnumerable `1[T] source, System.Func`
        2[T, TResult] predicate)[0x00011] in < ba85ba5122c3499483c4d8a7ac6f7e5a >: 0
    at Splat.PlatformBitmapLoader..cctor()[0x00026] in < b69f18e916c449f19b169602282b9d0f >: 0
        -- - End of inner exception stack trace-- -
        at(wrapper managed - to - native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod, object, object[], System.Exception & )
    at System.Reflection.MonoCMethod.InternalInvoke(System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions)[0x00005] in < 58604 b4522f748968296166e317b04b4 >: 0
        -- - End of inner exception stack trace-- -
        at System.Reflection.MonoCMethod.InternalInvoke(System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions)[0x0001a] in < 58604 b4522f748968296166e317b04b4 >: 0
    at System.RuntimeType.CreateInstanceMono(System.Boolean nonPublic, System.Boolean wrapExceptions)[0x000a8] in < 58604 b4522f748968296166e317b04b4 >: 0
    at System.RuntimeType.CreateInstanceSlow(System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark & stackMark)[0x00009] in < 58604 b4522f748968296166e317b04b4 >: 0
    at System.RuntimeType.CreateInstanceDefaultCtor(System.Boolean publicOnly, System.Booean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark & stackMark)[0x00027] in < 58604 b4522f748968296166e317b04b4 >: 0
    at System.Activator.CreateInstance(System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions)[0x0002c] in < 58604 b4522f748968296166e317b04b4 >: 0
    at System.Activator.CreateInstance(System.Type type, System.Boolean nonPublic)[0x00000] in < 58604 b4522f748968296166e317b04b4 >: 0
    at System.Activator.CreateInstance(System.Type type)[0x00000] in < 58604 b4522f748968296166e317b04b4 >: 0
    at Splat.AssemblyFinder.AttemptToLoadType[T](System.String fullTypeName)[0x000bb] in < b69f18e916c449f19b169602282b9d0f >: 0
    at Splat.BitmapLoader..cctor()[0x00000] in < b69f18e916c449f19b169602282b9d0f >: 0
}


{
    System.TypeInitializationException: The type initializer
    for 'Splat.PlatformBitmapLoader'
    threw an exception.-- - > System.InvalidOperationException: Sequence contains no matching element
    at System.Linq.Enumerable.First[TSource](System.Collections.Generic.IEnumerable `1[T] source, System.Func`
        2[T, TResult] predicate)[0x00011] in < ba85ba5122c3499483c4d8a7ac6f7e5a >: 0
    at Splat.PlatformBitmapLoader..cctor()[0x00026] in < b69f18e916c449f19b169602282b9d0f >: 0
        -- - End of inner exception stack trace-- -
        at(wrapper managed - to - native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod, object, object[], System.Exception & )
    at System.Reflection.MonoCMethod.InternalInvoke(System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions)[0x00005] in < 58604 b4522f748968296166e317b04b4 >: 0
}


{
    System.InvalidOperationException: Sequence contains no matching element
    at System.Linq.Enumerable.First[TSource](System.Collections.Generic.IEnumerable `1[T] source, System.Func`
        2[T, TResult] predicate)[0x00011] in < ba85ba5122c3499483c4d8a7ac6f7e5a >: 0
    at Splat.PlatformBitmapLoader..cctor()[0x00026] in < b69f18e916c449f19b169602282b9d0f >: 0
}
```

**Comment by glennawatson** [comment] 2019-05-28 12:07
What version of Android are you using?

**Comment by IamTobi** [comment] 2019-05-28 12:10
currently testing on android 7.0

**Comment by glennawatson** [comment] 2019-05-28 12:11
Ah that's be likely why. Our minimum is Android 81

**Comment by IamTobi** [comment] 2019-05-28 12:13
Devices with Android 9 and 8 are also not working

**Comment by glennawatson** [comment] 2019-05-28 12:16
I'm talking about in your target framework not so much the devices.

**Comment by IamTobi** [comment] 2019-05-28 12:17
Target is 8.1

**Comment by glennawatson** [comment] 2019-05-28 12:19
I will have a look at it tomorrow my time for you. See what I can find.

**Comment by alexshikov** [comment] 2019-06-07 18:50
We have similar crashes for users with on Android 8.0 devices according to Fabric...

**Comment by alexshikov** [comment] 2019-06-07 20:09
After some debug, there is a weird thing happening:

- `.GetAssemblies()` contains assembly with a name `__callback_factory__, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`.
- `SelectMany(x => x.GetTypes()` throws an excption for that assembly

```
Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Type '__callback_factory__class__' is not finished
```

**Comment by dpvreony** [comment] 2019-06-08 06:45
potential fix in #337 but is there a better way than to skip all dynamic assemblies if they could have a genuine use case for generating drawable resources via reflection? (not sure they do, merely posing the question)

@IamTobi unfortunately this won't be an immediate help to you if you are blocked on akavache 5\splat 3.

**Comment by alexshikov** [comment] 2019-06-10 13:08
Any idea oh how to use a local method for assembly loading?
Currently, the crash happening in a static constructor, so the path to `Splat.BitmapLoader.Current = new MyAndroidBitmapLoader()` can't be reached...
The NuGet package can't be removed, as there are a few other libraries that reference Splat.

So far the only workaround I see is to keep the original NuGet reference but replace the DLL reference in the project to the custom one (that built from the source code using fixed assembly loading).

Is there any better solution to try?

**Comment by dpvreony** [comment] 2019-06-10 22:27
just to clarify - do you mean having a custom splat v3?

what's blocking you getting onto v7?

moving forward we can probably do something to allow service locator registration of platformbitmap loader
``public static void InitializeSplat(this IMutableDependencyResolver resolver)``

**Comment by alexshikov** [comment] 2019-06-11 08:56
We have a bit outdated production that uses Splat 2.0.0, and development that the latest 7.2.1.
We can't easely update production to the newer version because of other libraries - to much hustle.

I've tried to follow the next approach:
1. Copy source code of `PlatformBitmapLoader` to the project from Splat 2.0.0 release
2. Modify `static PlatformBitmapLoader()` logic to fix an issue
3. On app setup replace plugin singleton with custom implementation `Splat.BitmapLoader.Current = new MyAndroidBitmapLoader()`

Usually that helps, but in the current case the problem happens before `.Current` setter invoked:
https://github.com/reactiveui/splat/blob/48fabe2087a21b11d9cdc1a19227888229239aa1/src/Splat/Bitmaps/BitmapLoader.cs#L18

Also, the latest Splat NuGet package still has the issue and we need the fix now.

**Comment by glennawatson** [comment] 2019-06-11 09:43
> Also, the latest Splat NuGet package still has the issue and we need the fix now.

I don't see you contributing to the project nor your employer? We don't commit to any sort of timeline since everyone here is basically volunteering their time. https://www.youtube.com/watch?v=Mm_RuObpeGo for some ideas why sometimes open source developers are jerks. 

Essentially @dpvreony when his life permits will get that fix out there in the wild, and if we have per our open collective policy https://opencollective.com/reactiveui be happy to give your issue priority.

Thanks.

**Comment by alexshikov** [comment] 2019-06-11 10:48
@glennawatson I'm sorry for being impolite. I didn't have attention to insult or force to fix an issue.

I just wanted to point out that I understand that the fix won't be available immediately, and we just looking for a local workaround while the new version is released.

Hoped to get your thoughts, if you see any better solution then described.

**Comment by glennawatson** [comment] 2019-06-11 11:36
I will see how far away @dpvreony is coming from the fix. That is a fairly standard reply if people start requesting changes immediately and stuff. There is definitely a problem where sometimes clients of open source products tend to expect guaranteed support levels and stuff so no offense intended and none taken.

**Comment by dpvreony** [comment] 2019-06-11 16:15
the challenge is splat v3 can't use an assembly rebind to v7.x because of the amount of breaking changes that have happened.

exceptions in static constructors basically mean the type is never available in the appdomain. the way the platformbitmap is set up makes it a bit difficult to retrospectively interact with. I touched on us changing the initialisation to allow injecting like you can do with the DI locator. but again that's future and won't solve your problem.

can you confirm you are using vs2017 or vs2019? other issues rearing their head recently are down to a change in vs2019 and xamarin. so if that's the case you could build with vs2017.

if you need a v2/v3 capable library you may to take a fork of v3 and copy the fix

https://github.com/mono/mono/blob/22887567e1663b101c37fa29ec1613175337f944/mcs/class/corlib/System.Reflection.Emit/AssemblyBuilder.cs#L820 is where the issue is occuring. I need to build a unit test and run it on the android test runner. I removed part of a fix on checking the dynamic type yesterday as I thought the try \ catch should handle it, but having looked at mono i'm not convinced.

**Comment by glennawatson** [comment] 2019-07-15 15:48
Was this fixed in v8 for you guys?

**Comment by dpvreony** [comment] 2019-07-15 22:20
followed up the quick fix with unit tests in test runner. and flexibility in the splat init to allow the default bitmap loader to be changed

![image](https://user-images.githubusercontent.com/170983/61252886-0c305c00-a757-11e9-80f7-f8c7ab9e6af8.png)

**Closed** 2019-07-15 22:46 UTC
Labels: Bug
