### ISSUE TITLE
[BUG] Can't install Splat.Autofac v, 9.4.5 with Autofac 5.2.0 

### ISSUE THREAD

**Issue by iashaik** [reactiveui/splat#520] opened 2020-05-28 11:03 UTC
**Describe the bug**
The prerequisite requirement for Splat.Autofac v. 9.4.5 is limited to Autofac 5.0. splat doesn't support the latest version of Autofac. 

**Steps To Reproduce**
Can't upgrade Splat from 9.4.1 to 9.4.5 with Autofac 5.2 installed.

**Comment by glennawatson** [comment] 2020-05-28 11:08
Duplicate of https://github.com/reactiveui/splat/issues/465

**Closed by glennawatson** 2020-05-28 11:08 UTC
