### ISSUE TITLE
Update Splat.Autofac to work with Autofac 5.0

### ISSUE THREAD

**Issue by ronaldvdv** [reactiveui/splat#465] opened 2020-02-03 13:26 UTC
**Describe the bug**
Starting with Autofac 5.0, containers are mutable. See corresponding [pull request](https://github.com/autofac/Autofac/pull/981) and [release notes](https://github.com/autofac/Autofac/releases/tag/v5.0.0) . This gives startup errors when using Splat.Autofac.

**Steps To Reproduce**
Provide the steps to reproduce the behavior:

- Install Splat.Autofac 9.3 and Autofac 5.0.0 packages
- In your startup code, call the IContainer.UseAutofacDependencyResolver() extension method.
- When running your application, this gives an exception: `Method not found: 'Void Autofac.ContainerBuilder.Update(Autofac.Core.IComponentRegistry)'`.

**Environment(please complete the following information):**
 - OS: Windows 10
 - Version: Autofac 5.0.0, Splat.Autofac 9.3

**Comment by glennawatson** [comment] 2020-02-03 16:51
Thanks for the report

This is related to https://github.com/reactiveui/splat/pull/463

**Comment by RLittlesII** [comment] 2020-02-19 03:50
Changing this to a feature request.  Autofac has breaking changes in their v5.0 API.  We don't support that API yet.

**Comment by ronaldvdv** [comment] 2020-02-19 05:43
Thanks, you're right! :-) And I would be interested in picking this up, too. Just from a design perspective I'm wondering - what is the main reason Splat was designed with mutable dependency containers in mind? What are the main things that would break or even become impossible (within Splat itself) without that? I can imagine if the problems within Splat are limited but many other projects depend on it, we could make a separate package Splat.Autofac5?

**Comment by RLittlesII** [comment] 2020-02-19 06:13
My thought would be it would be something we target for the next major release.  If we need to provide early access to the package itself we can use GitHub Packages to release a version if you are in a pressing need to migrate to Autofac 5.x

Autofac provided examples of how it could be done.  We just need to evaluate how to make those options work within the Splat Adapter.

As for Splat.  It is a service locator, it is a dependent library for ReactiveUI.  It was designed to be extremely lightweight and fast.  There is already discussions around how we are going to overhaul the initialization, splat will still be at the root of that.

**Comment by ronaldvdv** [comment] 2020-02-20 07:32
Indeed I looked at some of the open discussions in the ReactiveUI repository - it seems there are multiple :-D Not sure how to contribute best, but I guess the more difficult questions to be answered first are on ReactiveUI side. If we want ReactiveUI to cooperate nicely with DI frameworks that separate the service registration phase from the service resolving phase, the initialization "magic" in ReactiveUI needs a bit of redesigning ([issue](https://github.com/reactiveui/ReactiveUI/issues/1737) and [rfc] (https://github.com/reactiveui/rfcs/issues/14)) and follow these same two steps.

Perhaps a quick fix could be, that we have a mutable dependency resolver adapter for Autofac. It gets an original IContainer as a constructor argument. Whenever it is asked to make changes, it creates a new lifetime scope ([see Autofac documentation](https://autofaccn.readthedocs.io/en/latest/lifetime/working-with-scopes.html)) and then stores the updated container. Requests for resolving services are always forwarded to the most recent container.

This would not work perfectly if applications also create their own lifetime scopes - those scopes would never see the changes made using the mutable dependency resolver...

**Comment by skaman** [comment] 2020-08-14 17:16
Any news about this?

**Comment by skaman** [comment] 2020-08-16 12:51
At the moment I ended up to this workaround. It's far to be elegant but, until Splat will not correctly support it, this work for my needs.

In my case I'd like to use ReactiveUI with Blazor server and Autofac 5. The AutofacDependencyResolver will register every type to 2 differents ContainerBuilder. One is internal and is used to satisfy Splat (calling multiple times the BeginLifetimeScope to workaround the immutability), and the other one is the real ContainerBuilder of my application.

Here the custom AutofacDependencyResolver: https://gist.github.com/skaman/39506a11657dbaae69101eeeb3e4a5e0

Inside the startup, I used it in this way
```
public void ConfigureContainer(ContainerBuilder builder)
{
    var resolver = new AutofacDependencyResolver(builder);
    Locator.SetLocator(resolver);

    Locator.CurrentMutable.InitializeReactiveUI();

    builder.RegisterInstance(resolver);

    builder.RegisterType<MyType1>();
    builder.RegisterType<MyType2>();
    // and so on ...
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env, QldbService qldbService)
{
    var lifetimeScope = app.ApplicationServices.GetAutofacRoot();
    var resolver = lifetimeScope.Resolve<AutofacDependencyResolver>();
    resolver.SetLifetimeScope(lifetimeScope);

    // continue with normal configure flow ...
}
```

**Comment by glennawatson** [comment] 2020-08-16 12:55
Thanks

Until autofac allows some sort of mutability this might be the only way.

**Comment by HrlecMatej** [comment] 2020-09-17 09:15
I doubt that's likely to change, since the Autofac's Update method was removed so that containers can be generally immutable.

**Comment by glennawatson** [comment] 2020-09-17 09:19
We're unlikely to support autofac going into the future due to it.

**Comment by skaman** [comment] 2020-09-17 09:20
> I doubt that's likely to change, since the Autofac's Update method was removed so that containers can be generally immutable.

I agree, immutability is a feature in autofac 5.x: https://autofaccn.readthedocs.io/en/latest/best-practices/#consider-a-container-as-immutable

**Comment by glennawatson** [comment] 2020-09-17 09:22
Closing this issue since we are just not going to support autofac 5

**Closed by glennawatson** 2020-09-17 09:22 UTC
Labels: Feature, up-for-grabs

**Comment by skaman** [comment] 2020-09-17 09:30
May I ask, if you know, some suggestion about an alternative IoC container that is compatible with Splat and full featured like autofac? The main feature that i need in my project is the child scopes

**Comment by glennawatson** [comment] 2020-09-17 12:01
I'll research and get back to you on that one

**Comment by HrlecMatej** [comment] 2020-09-17 13:24
Autofac is the most popular .NET DI (at least by Github Stars), so I would probably not be the only one, who would prefer for a solution to be found.
skaman's workaround could perhaps be built upon, since child lifetime scopes are the only way Autofac supports any dynamic registrations.

**Comment by glennawatson** [comment] 2020-09-17 13:25
Hey there. locking this thread from further conversation.

**Comment by glennawatson** [comment] 2020-09-17 13:28
We will welcome pr for this issue but this is not a priority of the team at the moment.

**Comment by glennawatson** [comment] 2020-09-18 05:00
Unlocked in case anyone wants to work out contact details to discuss offline for providing their own PR to splat.

**Comment by HrlecMatej** [comment] 2020-09-18 09:31
This is my attempt at a PR. Thank you to "skaman" for coming up with the workaround.
