### ISSUE TITLE
Make `DebugLogger` internal

### ISSUE THREAD

**Issue by johannesegger** [reactiveui/splat#123] opened 2015-10-16 06:16 UTC
It just took me 1 hour to realize why `DebugLogger` doesn't log anything (it's because it uses `Debug.WriteLine` which gets thrown away when compiling in release mode). Maybe the default logger should be `NullLogger` and `DebugLogger` should be internal?

**Comment by ghuntley** [comment] 2016-01-15 08:13
We were just discussing this over in the ReactiveUI slack channel. 

> Matt: 

Splat has a debug logger, but it doesn't work. 

> Paul Betts:

Console.WriteLine doesn't exist on all platforms. Which is why it's not in-box in the first place

> Geoff:

Why don't we ship platform specific implementations by default. Do or Don't enable it for them by default (my vote is dont). Whatever the analogue of Console.Writeline is,  send the output there so it shows up in the dev environment. The landscape right now is consumers of the project implement the interface and basically do that anyway right?

> Ryan

You can do Debug.WriteLine from a PCL but it does at least output to the output window :tada:

> Paul Betts: 

Debug.WriteLine is useless in a library because it gets stripped from release builds. There is ​_no_​ way a library compiled for Release build can write to the debug output window in UWP apps

Geoff: 

> What if we shipped a nuget package that installed a `.cs` into their solution? Yes that behaviour is annoying but  better than asking people to wire up the logger.

Paul Betts:

> This isn't a terrible idea tbh

**Comment by eggapauli** [comment] 2016-01-18 05:47
Ohh ok, so I guess this issue is somewhat superfluous. Feel free to close it and thanks for posting the conversation.

**Comment by ghuntley** [comment] 2016-01-18 10:48
np, you should come join us in Slack :-)

We will keep the issue open because right now the default logging w/Splat sucks until such a time it doesn't.

**Comment by NZSmartie** [comment] 2017-09-26 18:52
ASPNet Core's Debug Logger solves this by `#define DEBUG` as seen here 
https://github.com/aspnet/Logging/blob/rel/2.0.0/src/Microsoft.Extensions.Logging.Debug/DebugLogger.debug.cs#L7

The catch is that the debug function itself is in a separate file to prevent unintended behaviour from happening that may be caused by `DEBUG` being present.

**Comment by ghuntley** [comment] 2017-09-26 21:04
@nzsmartie. You legend! Send in the PR please (plus that super super handy comment explaining why)

**Closed** 2018-11-21 03:15 UTC
Labels: proposal, up-for-grabs
