### ISSUE TITLE
[BUG] VS2019 Crash in BitmapLoader Constructer (Android)

### ISSUE THREAD

**Issue by leoMehlig** [reactiveui/splat#317] opened 2019-04-03 08:28 UTC
**Describe the bug**
Since updating Xamarin, I get an crash in the `BitmpaLoader` constructor on Android, because the `Resource` type is in the second assembly.

I did a bit of digging and the app assembly is now at index 105 (which I suppose is random). I'm not sure how to find out which assembly is the right one, but the current approach (always pick the second) seems to be broken. 

**Environment(please complete the following information):**
 - OS: Droid
 - Xanmarin.Forms: 3.6.0

**Comment by glennawatson** [comment] 2019-04-03 14:32
Mind providing a small demo of your problem?

**Comment by leoMehlig** [comment] 2019-04-04 09:41
Here you go: [Crash Demo](https://1drv.ms/u/s!AqYxkz1lMfsTulpQmQpPa_rE8nGE)
Just run it on an android device/emulator and it should crash on startup.

**Comment by glennawatson** [comment] 2019-04-04 09:42
Cool thanks. Likely to be late next week before I can personally look at the problem but others might be able to look at it sooner.

**Comment by dpvreony** [comment] 2019-04-04 14:45
I've tested your repo on Android8.1 (Oreo) API27 and it loads in emulator without a crash.

Can you confirm emulator and sdk versions please

![image](https://user-images.githubusercontent.com/170983/55560730-c3ddb880-56e8-11e9-923a-119723019854.png)

**Comment by dpvreony** [comment] 2019-04-04 20:31
reproduced in vs2019

**Comment by dpvreony** [comment] 2019-04-04 20:38
similar issue in assembly resolving in https://github.com/reactiveui/ReactiveUI/issues/1993

**Comment by dpvreony** [comment] 2019-04-05 18:22
done a potential fix but it needs a review

**Comment by RLittlesII** [comment] 2019-04-09 19:21
@dpvreony Is this possibly related to https://github.com/reactiveui/ReactiveUI/issues/1993

**Comment by dpvreony** [comment] 2019-04-09 20:25
@RLittlesII looks like it, yes. it assumes the resource dll is always specific position in array, which is no longer the case. also (if I've understood it correct) assumes that there is only a single assembly you need to look at and look only at its assemblies. if there's any DI\plug ins into the AppDomain this doesn't work?

i didn't do ExecutingAssembly \ EntryPoint as i think it can be thrown out by the unit tests as well, and support within AppDomain on netstandard isn't there.

code is almost identical apart from splat filtering by drawing types.

the runner in the PR allows the xunit tests to be run on an android device\emulator. i can look to add it to ReactiveUI later this week

**Comment by glennawatson** [comment] 2019-04-09 22:42
fixed in #317

**Closed by glennawatson** 2019-04-09 22:42 UTC
Labels: Bug
